name: Package

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  release:
    types:
      - published

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build and Publish
        id: build
        uses: wgtechlabs/package-build-flow-action@v2.1.0
        with:
          registry: both
          package-manager: bun
          build-script: build
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
